# Generated by Django 4.1.5 on 2023-01-06 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_test_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
